config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root to: 'warehouses#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
  
  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items

  enum status: {pending: 0, delivered: 1, canceled: 2}

  validates :expected_delivery_date, :code, presence: true
  validate :date_be_in_future

  before_validation :generate_code

  private

  def date_be_in_future
    if self.expected_delivery_date.present? && self.expected_delivery_date <= Date.today
      errors.add(:expected_delivery_date, "precisa estar no futuro.")
    end
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product_model
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  
  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :weight, :width, :height, :depth, comparison: {greater_than: 0}
  validates :sku, length: {is: 20}
  validates :sku, uniqueness: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :registration_number, uniqueness: true
  validates_format_of :registration_number, with: /\A\d{14}\z/, message: 'Deve fornecer 14 números'

  has_many :product_models


  def full_description
    "#{corporate_name} - #{brand_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :area, :address, :cep, :description, presence: true
  validates :name, :code, uniqueness: true
  validates_format_of :cep, with: /\A\d{5}-\d{3}\z/, message: "Deve estar no formato 00000-000"

  
  def full_description
    "#{code} - #{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_models, only: [:new, :create, :edit, :update]
  before_action :check_user, only: [:show, :edit, :update, :delivered, :canceled]


  def index
    @orders = current_user.orders
  end

  def show; end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      flash[:notice] = 'Pedido registrado com sucesso.'
      return redirect_to @order
    end

    flash.now[:notice] = 'Não foi possível criar pedido.'
    render :new
  end

  def edit; end

  def update
    if @order.update(order_params)
      flash[:notice] = 'Pedido atualizado com sucesso!'
      return redirect_to order_path(@order)
    end

    flash.now[:notice] = 'Não foi possível atualizar o pedido.'
    render :edit
  end

  def search
    @query = params[:query]
    @orders = Order.where('code LIKE ?', "%#{@query}%")

    redirect_to @orders.first if @orders.count == 1
  end

  def delivered
    @order = Order.find(params[:id])
    @order.delivered!

    redirect_to order_path(@order)
  end

  def canceled
    @order = Order.find(params[:id])
    @order.canceled!

    redirect_to order_path(@order)
  end

  private

  def check_user
    @order = Order.find params[:id]

    if @order.user != current_user
      flash[:alert] = 'Acesso não permitido.'
      redirect_to root_path
    end
  end

  def order_params
    params.require(:order).permit(
      :warehouse_id, :supplier_id, :expected_delivery_date
    )
  end

  def load_models
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :find_product_model, only: [:show]
  before_action :set_product_model, only: [:create]


  def index
    @product_models = ProductModel.all
  end

  def show; end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    if @product_model.save
      return redirect_to @product_model
    end

    @suppliers = Supplier.all
    flash.now[:notice] = 'Não foi possível criar modelo de produto'
    render :new
  end

  private

  def find_product_model
    @product_model = ProductModel.find(params[:id])
  end

  def set_product_model
    params_product_model = params.require(:product_model).permit(
      :name, :weight, :width, :height, :depth, :sku, :supplier_id
    )

    @product_model = ProductModel.new params_product_model
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :find_supplier, except: [:index, :new, :create]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def edit; end

  def create
    @supplier = Supplier.new(suppliers_params)
    
    if @supplier.save
      flash[:notice] = 'Fornecedor cadastrado com sucesso.'
      return redirect_to @supplier
    end
    
    flash[:notice] = 'Não foi possível cadastrar fornecedor.'
    render 'new'
  end

  def update
    if @supplier.update(suppliers_params)
      flash[:notice] = 'Cadastrado atualizado com sucesso.'
      return redirect_to @supplier
    end
  
    flash[:notice] = 'Não foi possível atualizar fornecedor.'
    render 'edit'
  end

  private

  def suppliers_params
    params.require(:supplier).permit(
      :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email
    )
  end

  def find_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  def index
    @warehouses = Warehouse.all
  end

  def show; end

  def new
    @warehouse = Warehouse.new
  end
  
  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      return redirect_to root_path, notice: 'Galpão cadastrado com sucesso'
    end

    flash.now[:notice] = 'Galpão não cadastrado'
    render :new
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      flash[:notice] = 'Galpão atualizado com sucesso.'
      return redirect_to @warehouse
    end

    flash.now[:notice] = 'Não foi possível atualizar o galpão.'
    render :edit
  end

  def destroy
    @warehouse.destroy
    flash[:notice] = 'Galpão removido com sucesso.'
    redirect_to root_path
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find params[:id]
  end

  def warehouse_params
    params.require(:warehouse).permit(
      :name, :code, :city, :address, :cep, :area, :description
    )
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_models_helper.rb
module ProductModelsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1>Galpões & Estoques</h1>

      <nav>
        <div><%= link_to "Home", root_path %></div>
        <div><%= link_to "Fornecedores", suppliers_path %></div>
        <div><%= link_to "Modelos de produto", product_models_path %></div>
        <div><%= link_to "Registrar pedido", new_order_path %></div>
        
        <div>
          <% if user_signed_in? %>
            <%= current_user.name %>
            <%= button_to "Sair", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Entrar", new_user_session_path %>
            <%= link_to "Criar conta", new_user_registration_path %>
          <% end %>
        </div>

        <% if user_signed_in? %>
          <div>
            <%= form_with url: search_orders_path, method: :get do |f| %>
              <%= f.label :query, 'Buscar pedido' %>
              <%= f.text_field :query %>
              <%= f.submit "Buscar" %>
            <% end %>
          </div>

          <%= link_to 'Meus Pedidos', orders_path %>

        <% end %>
      </nav>

      <div>
        <p><%= alert %></p>
        <p><%= notice %></p>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with model: @order do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id , @suppliers, :id, :full_description %>
  </div>

  <div>
    <%= f.label :expected_delivery_date %>
    <%= f.date_field :expected_delivery_date %>
  </div>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/orders/_order.html.erb
<div>
  <p>Pedido: <%= link_to order.code, order %></p>
  <p>Galpão de destino: <%= order.warehouse.code %></p>
  <p>Fornecedor: <%= order.supplier.brand_name %></p>
  <p>Usuário: <%= order.user.name %></p>
  <p>Previsão de entrega: <%= l order.expected_delivery_date %></p>
</div>

app/views/orders/edit.html.erb
<section>
  <%= render 'form' %>
</section>

app/views/orders/index.html.erb
<section>
  <h2>Meus pedidos</h2>

  <% if @orders.empty? %>
    <div>
      <p>Você não tem pedidos cadastrados.<p>
    </div>
  <% end %>

  <div>
    <%= render @orders %>
  </div>
</section>

app/views/orders/new.html.erb
<section>
  <%= render 'form' %>
</section>

app/views/orders/search.html.erb
<section>
  <% if @orders.any? %>
    <h2>
      <%= pluralize @orders.count, 'pedido encontrado', 'pedidos encontrados' %>
      para: <%= @query %>
    </h2>
  <% else %>
    <p>Não foi encontrado correspondência para: <%= @query %></p>
  <% end %>

  <%= render @orders %>

</section>

app/views/orders/show.html.erb
<section>
  <div>
    <h2><%= Order.model_name.human %> <%= @order.code %></h2>
    
    <div>
      <p><%= Warehouse.model_name.human %>: <%= @order.warehouse.full_description %></p>
    </div>

    <div>
      <p><%= Supplier.model_name.human %>: <%= @order.supplier.full_description %></p>
    </div>
      
    <div>
      <p><%= Order.human_attribute_name :user %>: <%= @order.user.name %></p>
    </div>

    <div>
      <p><%= t :user_contact %>: <%= @order.user.email %></p>
    </div>
    
    <div>
      <p><%= Order.human_attribute_name :expected_delivery_date %>: <%= l @order.expected_delivery_date %></p>
    </div>

    <div>
      <p><%= Order.human_attribute_name :status %>: <%= t @order.status %></p>
    </div>
    
  </div>

  <div>
    <%= button_to 'Marcar como ENTREGUE', delivered_order_path, method: :post %>
    <%= button_to 'Marcar como CANCELADO', canceled_order_path, method: :post %>

    <%= link_to "Editar", edit_order_path %>
  </div>

  <div>
    <h3>Itens do pedido</h3>

    <% @order.order_items.each do |item| %>
      <p><%= item.quantity %> x <%= item.product_model.name %></p>
    <% end %>
  </div>
</section>

app/views/product_models/_form.html.erb
<%= form_with model: @product_model do |f| %>
  <div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :weight %>
		<%= f.number_field :weight %>
	</div>

	<div>
		<%= f.label :width %>
		<%= f.number_field :width %>
	</div>

	<div>
		<%= f.label :height %>
		<%= f.number_field :height %>
	</div>

	<div>
		<%= f.label :depth %>
		<%= f.number_field :depth %>
	</div>

	<div>
		<%= f.label :sku %>
		<%= f.text_field :sku %>
	</div>

	<div>
		<%= f.label :supplier_id %>
		<%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
	</div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/product_models/_product_model.html.erb
<div>
  <%= link_to product_model do %>
    <p><%= product_model.name %> (<%= product_model.supplier.brand_name %>)</p>
  <% end %>

  <% if controller_name == 'supplier' %>
    <p>
      <%= product_model.width %>cm x
      <%= product_model.height %>cm x
      <%= product_model.depth %>cm
    </p>
  <% end %>

  <p><%= product_model.sku %></p>
</div>

app/views/product_models/index.html.erb
<section>
  <div>
    <%= link_to "Cadastrar modelo", new_product_model_path %>
  </div>
  
  <% @product_models.each do |pm| %>
    <%= render pm %>
  <% end %>

  <% if @product_models.empty? %>
    <div>
      <p>Não existe nenhum modelo de produto cadastrado.</p>
    </div>
  <% end %>
</section>

app/views/product_models/show.html.erb
<section>
  <div>
    <h2>Impressora Multifuncional</h2>
    
    <p>Fornecedor: <%= @product_model.supplier.brand_name %></p>
    
    <p>Peso: <%= @product_model.weight %>g</p>
    
    <p>Dimensão:
      <%= @product_model.width %>cm x
      <%= @product_model.height %>cm x
      <%= @product_model.depth %>cm
    </p>

    <p>SKU: <%= @product_model.sku %></p>
  </div>
</section>

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f| %>
	<div>
		<%= f.label :corporate_name %>
		<%= f.text_field :corporate_name %>
	</div>

	<div>
		<%= f.label :brand_name %>
		<%= f.text_field :brand_name %>
	</div>

	<div>
		<%= f.label :registration_number %>
		<%= f.text_field :registration_number %>
	</div>

	<div>
		<%= f.label :full_address %>
		<%= f.text_field :full_address %>
	</div>

	<div>
		<%= f.label :city %>
		<%= f.text_field :city %>
	</div>

	<div>
		<%= f.label :state %>
		<%= f.text_field :state %>
	</div>

	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/suppliers/edit.html.erb
<section>
  <h2>Editar fornecedor</h2>

  <%= render 'form' %>

</section>

app/views/suppliers/index.html.erb
<section>
  <h2>Fornecedores</h2>

  <%= link_to "Cadastrar fornecedor", new_supplier_path %>

  <div>
    <% @suppliers.each do |s| %>
      <div>
        <%= link_to s.brand_name, s %>
        <div>
          <p><%= s.city %> - <%= s.state %></p>
        </div>
      </div>
    <% end %>

    <% if @suppliers.empty? %>
      <p>Não existem fornecedores cadastrados.</p>
    <% end %>
  </div>

</section>

app/views/suppliers/new.html.erb
<section>
  <h2>Registrar fornecedor</h2>

  <%= render 'form' %>

</section>

app/views/suppliers/show.html.erb
<section>
  <div>
    <div >
      <p><%= @supplier.corporate_name %> (<%= @supplier.brand_name %>)</p>
    </div>

    <div>
      <p>CNPJ: <%= @supplier.registration_number %></p>
    </div>

    <div>
      <p>Endereço: <%= @supplier.full_address %></p>
    </div>

    <div>
      <p>Cidade: <%= @supplier.city %> - <%= @supplier.state %></p>
    </div>

    <div>
      <p>Email: <%= @supplier.email %></p>
    </div>
  </div>

  <div>
    <%= link_to "Editar", edit_supplier_path %>
  </div>

  <div>
    <% @supplier.product_models.each do |pm| %>
      <%= render pm %>
    <% end %>
  </div>

</section>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  
  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
      
  <div>
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>
      
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <%= f.submit 'Enviar' %>
  
<% end %>

app/views/warehouses/edit.html.erb
<section>
  <h2>Editar Galpão<h2>

  <%= render 'form' %>
</section>

app/views/warehouses/index.html.erb
<section id='warehouses'>
  <h2>Galpões</h2>

  <div>
    <%= link_to 'Cadastrar galpão', new_warehouse_path %>
  </div>

  <% @warehouses.each do |warehouse| %>
    <div>
      <dl>
        <dt>Nome:</dt>
        <dd><%= link_to warehouse.name, warehouse %></dd>

        <dt>Código:</dt>
        <dd><%= warehouse.code %></dd>

        <dt>Cidade:</dt>
        <dd><%= warehouse.city %></dd>

        <dt>Área:</dt>
        <dd><%= warehouse.area.to_fs(:delimited, delimiter: '.') %> m2</dd>
      </dl>
    </div>
  <% end %>

  <% if @warehouses.empty? %>
    <p>Não há galpões cadastrados</p>
  <% end %>
</section>

app/views/warehouses/new.html.erb
<section>
  <h1>Novo galpão</h1>
  
  <%= render 'form' %>
</section>

app/views/warehouses/show.html.erb
<section>
  <h2>Galpão <%= @warehouse.code %></h2>
  <div>
    <dl>
      <dt>Nome:</dt>
      <dd><%= @warehouse.name %></dd>
      
      <dt>Cidade:</dt>
      <dd><%= @warehouse.city %></dd>
      
      <dt>Área:</dt>
      <dd><%= @warehouse.area.to_fs(:delimited, delimiter: '.') %> m2</dd>
      
      <dt>Endereço:</dt>
      <dd><%= @warehouse.address %></dd>
      
      <dt>CEP:</dt>
      <dd><%= @warehouse.cep %></dd>

      <dt>Descrição:</dt>
      <dd><%= @warehouse.description %></dd>
  </div>

  <%= link_to 'Voltar', root_path %>
  <%= link_to 'Editar', edit_warehouse_path %>
  <%= button_to 'Remover', warehouse_path, method: :delete %>

</section>